langage: java

jdk: openjdk8

env:
  - CODECOV_TOKEN="a1ebc902-f22d-4073-b49e-b666cbc95538"

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d

before_script:
  - cd ../../src

script:
  - mvn clean test -Ptest-consumer,test-business

after_script:
  - cd ../docker/dev
  - docker-compose stop

after_success:
  - bash <(curl -s https://codecov.io/bash)